### ISSUE TITLE
WiFi модуль должен быть включен при запуске приложения

### ISSUE THREAD

**Issue by bukhantsov** [vadim6810/WeKast-Dongle#1]
Программа не работает, если WiFi модуль выключен. Нужно его включить.
Также при включении устройства, нужно включить WiFi модуль, чтобы приложение загрузилось.

**Comment by android-leha** [comment]
Его же можно программно включать

**Comment by bukhantsov** [comment]
Можно. Включаю, но пока он включиться попытка подключения к WiFi проходит. Как подождать пока он включится? А потом к нему подключаться. Thread sleep чего то не получается.
